// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"SwaggerPostGresApi/models"
)

// UpdateUserByIDOKCode is the HTTP code returned for type UpdateUserByIDOK
const UpdateUserByIDOKCode int = 200

/*
UpdateUserByIDOK User updated successfully

swagger:response updateUserByIdOK
*/
type UpdateUserByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewUpdateUserByIDOK creates UpdateUserByIDOK with default headers values
func NewUpdateUserByIDOK() *UpdateUserByIDOK {

	return &UpdateUserByIDOK{}
}

// WithPayload adds the payload to the update user by Id o k response
func (o *UpdateUserByIDOK) WithPayload(payload *models.User) *UpdateUserByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user by Id o k response
func (o *UpdateUserByIDOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateUserByIDNotFoundCode is the HTTP code returned for type UpdateUserByIDNotFound
const UpdateUserByIDNotFoundCode int = 404

/*
UpdateUserByIDNotFound User not found

swagger:response updateUserByIdNotFound
*/
type UpdateUserByIDNotFound struct {
}

// NewUpdateUserByIDNotFound creates UpdateUserByIDNotFound with default headers values
func NewUpdateUserByIDNotFound() *UpdateUserByIDNotFound {

	return &UpdateUserByIDNotFound{}
}

// WriteResponse to the client
func (o *UpdateUserByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateUserByIDInternalServerErrorCode is the HTTP code returned for type UpdateUserByIDInternalServerError
const UpdateUserByIDInternalServerErrorCode int = 500

/*
UpdateUserByIDInternalServerError Internal server error

swagger:response updateUserByIdInternalServerError
*/
type UpdateUserByIDInternalServerError struct {
}

// NewUpdateUserByIDInternalServerError creates UpdateUserByIDInternalServerError with default headers values
func NewUpdateUserByIDInternalServerError() *UpdateUserByIDInternalServerError {

	return &UpdateUserByIDInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateUserByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
